import os
import re
import sys

# 英文到法语的基本翻译映射
translations = {
    # 标题和常见短语
    "Bird Photography Tips": "Conseils de Photographie d'Oiseaux",
    "Capture the beauty and behavior of birds with these essential photography techniques": "Capturez la beauté et le comportement des oiseaux avec ces techniques de photographie essentielles",
    "Essential Camera Equipment": "Équipement Photo Essentiel",
    "Camera Settings for Birds": "Réglages de l'Appareil Photo pour les Oiseaux",
    "Understanding avian behavior": "Comprendre le comportement des oiseaux",
    "Composition Techniques": "Techniques de Composition",
    "Ethical Considerations": "Considérations Éthiques",
    "Post-Processing Tips": "Conseils de Post-Traitement",
    
    # 常见词汇
    "bird": "oiseau",
    "birds": "oiseaux",
    "photography": "photographie",
    "camera": "appareil photo",
    "lens": "objectif",
    "telephoto": "téléobjectif",
    "shutter": "obturateur",
    "aperture": "ouverture",
    "ISO": "ISO",
    "RAW": "RAW",
    "DSLR": "DSLR",
    "Mirrorless": "Sans Miroir",
    "Superzoom": "Superzoom",
    "Smartphone": "Smartphone",
    "adapter": "adaptateur",
    "behavior": "comportement",
    "avian": "aviaire",
    "perched": "perché",
    "flight": "vol",
    "nest": "nid",
    "nesting": "nidification",
    "welfare": "bien-être",
    "image": "image",
    "photo": "photo",
    "composition": "composition",
    "technique": "technique",
    "settings": "réglages",
    "mode": "mode",
    "manual": "manuel",
    "priority": "priorité",
    "autofocus": "autofocus",
    "continuous": "continu",
    "burst": "rafale",
    "depth of field": "profondeur de champ",
    "rule of thirds": "règle des tiers",
    "eye level": "niveau des yeux",
    "editing": "édition",
    "processing": "traitement",
    "crop": "recadrer",
    "noise reduction": "réduction du bruit",
    "quality": "qualité",
    "flexibility": "flexibilité",
    "wildlife": "faune",
    "nature": "nature",
    "dynamic": "dynamique",
    "success": "succès",
    "requires": "nécessite",
    "understanding": "compréhension",
    "patience": "patience",
    "approach": "approche",
    "avoid": "éviter",
    "sudden": "soudain",
    "movements": "mouvements",
    "natural": "naturel",
    "cover": "couverture",
    "trees": "arbres",
    "blinds": "caches",
    "possible": "possible",
    "many": "nombreux",
    "predictable": "prévisible",
    "routines": "routines",
    "observe": "observer",
    "shooting": "prise de vue",
    "anticipate": "anticiper",
    "best": "meilleur",
    "moments": "moments",
    "apply": "appliquer",
    "placing": "placer",
    "along": "le long",
    "intersection": "intersection",
    "points": "points",
    "ensure": "assurer",
    "sharp": "net",
    "well-lit": "bien éclairé",
    "critical": "critique",
    "element": "élément",
    "portrait": "portrait",
    "leave": "laisser",
    "space": "espace",
    "direction": "direction",
    "looking": "regardant",
    "moving": "se déplaçant",
    "capture": "capturer",
    "interaction": "interaction",
    "use": "utiliser",
    "shallow": "peu profond",
    "isolate": "isoler",
    "subjects": "sujets",
    "include": "inclure",
    "environmental": "environnemental",
    "context": "contexte",
    "shoot": "photographier",
    "engaging": "attrayant",
    "images": "images",
    "always": "toujours",
    "prioritize": "prioriser",
    "over": "plutôt que",
    "getting": "obtenir",
    "shot": "prise de vue",
    "maintain": "maintenir",
    "appropriate": "approprié",
    "distances": "distances",
    "disturbing": "perturber",
    "nests": "nids",
    "roosting": "repos",
    "sites": "sites",
    "never": "jamais",
    "playback": "lecture",
    "near": "près",
    "respect": "respecter",
    "private": "privé",
    "property": "propriété",
    "protected": "protégé",
    "areas": "zones",
    "format": "format",
    "maximum": "maximum",
    "enhancing": "améliorer",
    "natural": "naturel",
    "colors": "couleurs",
    "details": "détails",
    "rather": "plutôt",
    "than": "que",
    "judiciously": "judicieusement",
    "improve": "améliorer",
    "software": "logiciel",
    "help": "aider",
    "high": "élevé",
    "practice": "pratique",
    "makes": "rend",
    "perfect": "parfait",
    "start": "commencer",
    "common": "commun",
    "approachable": "accessible",
    "species": "espèces",
    "backyard": "jardin",
    "local": "local",
    "parks": "parcs",
    "skills": "compétences",
    "develop": "développer",
    "tackle": "aborder",
    "challenging": "difficile",
    "subjects": "sujets",
    "situations": "situations",
    "remember": "rappelez-vous",
    "that": "que",
    "the": "le",
    "is": "est",
    "you": "vous",
    "have": "avez",
    "with": "avec",
    "your": "votre",
    "and": "et",
    "for": "pour",
    "in": "dans",
    "of": "de",
    "to": "à",
    "a": "un",
    "an": "un",
    "as": "comme",
    "at": "à",
    "by": "par",
    "can": "peut",
    "from": "de",
    "it": "il",
    "more": "plus",
    "most": "la plupart",
    "on": "sur",
    "or": "ou",
    "this": "ce",
    "while": "tandis que",
    "who": "qui",
    "will": "va",
    "when": "quand",
    "which": "qui",
    "what": "quoi",
    "where": "où",
    "why": "pourquoi",
    "how": "comment",
    "all": "tous",
    "any": "tout",
    "some": "certains",
    "such": "tel",
    "no": "non",
    "not": "pas",
    "only": "seulement",
    "very": "très",
    "also": "aussi",
    "but": "mais",
    "if": "si",
    "so": "donc",
    "about": "à propos",
    "after": "après",
    "before": "avant",
    "between": "entre",
    "during": "pendant",
    "under": "sous",
    "through": "à travers",
    "throughout": "tout au long",
    "within": "dans",
    "without": "sans",
    "against": "contre",
    "among": "parmi",
    "beside": "à côté",
    "beyond": "au-delà",
    "into": "dans",
    "onto": "sur",
    "upon": "sur",
    "across": "à travers",
    "along": "le long",
    "around": "autour",
    "down": "bas",
    "up": "haut",
    "off": "désactivé",
    "over": "sur",
    "past": "passé",
    "since": "depuis",
    "till": "jusqu'à",
    "until": "jusqu'à",
    "above": "au-dessus",
    "below": "en dessous",
    "behind": "derrière",
    "beneath": "sous",
    "beside": "à côté",
    "besides": "en plus",
    "inside": "à l'intérieur",
    "outside": "à l'extérieur",
    "underneath": "en dessous",
    "because": "parce que",
    "though": "bien que",
    "although": "bien que",
    "unless": "à moins que",
    "whereas": "alors que",
    "whether": "si",
    "while": "tandis que",
    "once": "une fois",
    "since": "depuis",
    "till": "jusqu'à",
    "until": "jusqu'à",
    "whenever": "chaque fois que",
    "wherever": "partout où",
    "as": "comme",
    "even": "même",
    "just": "juste",
    "still": "encore",
    "too": "aussi",
    "already": "déjà",
    "always": "toujours",
    "never": "jamais",
    "often": "souvent",
    "rarely": "rarement",
    "seldom": "rarement",
    "sometimes": "parfois",
    "usually": "habituellement",
    "almost": "presque",
    "hardly": "à peine",
    "nearly": "presque",
    "quite": "assez",
    "rather": "plutôt",
    "somewhat": "quelque peu",
    "enough": "assez",
    "plenty": "beaucoup",
    "several": "plusieurs",
    "few": "peu",
    "little": "peu",
    "many": "beaucoup",
    "much": "beaucoup",
    "most": "la plupart",
    "all": "tous",
    "any": "tout",
    "each": "chaque",
    "every": "chaque",
    "no": "non",
    "none": "aucun",
    "some": "certains",
    "both": "les deux",
    "either": "soit",
    "neither": "ni",
    "other": "autre",
    "another": "un autre",
    "others": "autres",
    "such": "tel",
    "that": "ce",
    "these": "ces",
    "this": "ce",
    "those": "ces",
    "what": "quoi",
    "whatever": "peu importe",
    "which": "lequel",
    "whichever": "n'importe lequel",
    "who": "qui",
    "whoever": "quiconque",
    "whom": "qui",
    "whomever": "qui que ce soit",
    "whose": "dont",
    "anyone": "n'importe qui",
    "everybody": "tout le monde",
    "everyone": "tout le monde",
    "nobody": "personne",
    "somebody": "quelqu'un",
    "someone": "quelqu'un",
    "anything": "n'importe quoi",
    "everything": "tout",
    "nothing": "rien",
    "something": "quelque chose",
    "anywhere": "n'importe où",
    "everywhere": "partout",
    "nowhere": "nulle part",
    "somewhere": "quelque part",
    "anyhow": "de toute façon",
    "anyway": "quand même",
    "elsewhere": "ailleurs",
    "hence": "donc",
    "therefore": "par conséquent",
    "thus": "ainsi",
    "accordingly": "en conséquence",
    "consequently": "par conséquent",
    "instead": "au lieu",
    "meanwhile": "pendant ce temps",
    "moreover": "de plus",
    "nevertheless": "néanmoins",
    "nonetheless": "néanmoins",
    "otherwise": "autrement",
    "regardless": "indépendamment",
    "still": "encore",
    "then": "alors",
    "however": "cependant",
    "yet": "encore",
    "besides": "en plus",
    "furthermore": "en outre",
    "likewise": "de même",
    "similarly": "de même",
    "indeed": "en effet",
    "certainly": "certainement",
    "definitely": "définitivement",
    "naturally": "naturellement",
    "obviously": "évidemment",
    "of course": "bien sûr",
    "surely": "sûrement",
    "actually": "en fait",
    "as a matter of fact": "en fait",
    "in fact": "en fait",
    "in general": "en général",
    "generally": "généralement",
    "for example": "par exemple",
    "for instance": "par exemple",
    "in particular": "en particulier",
    "specifically": "spécifiquement",
    "especially": "particulièrement",
    "particularly": "particulièrement",
    "above all": "surtout",
    "chiefly": "principalement",
    "mainly": "principalement",
    "mostly": "principalement",
    "primarily": "principalement",
    "at least": "au moins",
    "finally": "finalement",
    "lastly": "enfin",
    "first": "premièrement",
    "second": "deuxièmement",
    "third": "troisièmement",
    "next": "ensuite",
    "then": "puis",
    "after that": "après cela",
    "afterward": "après",
    "subsequently": "par la suite",
    "previously": "précédemment",
    "earlier": "plus tôt",
    "initially": "initialement",
    "later": "plus tard",
    "soon": "bientôt",
    "suddenly": "soudainement",
    "gradually": "progressivement",
    "immediately": "immédiatement",
    "instantly": "instantanément",
    "promptly": "rapidement",
    "quickly": "rapidement",
    "slowly": "lentement",
    "briefly": "brièvement",
    "temporarily": "temporairement",
    "permanently": "de façon permanente",
    "occasionally": "occasionnellement",
    "periodically": "périodiquement",
    "regularly": "régulièrement",
    "frequently": "fréquemment",
    "constantly": "constamment",
    "continuously": "continuellement",
    "repeatedly": "à plusieurs reprises",
    "again": "encore",
    "once more": "encore une fois",
    "over and over": "encore et encore",
    "time and again": "maintes fois",
    "day": "jour",
    "night": "nuit",
    "morning": "matin",
    "afternoon": "après-midi",
    "evening": "soir",
    "today": "aujourd'hui",
    "tomorrow": "demain",
    "yesterday": "hier",
    "now": "maintenant",
    "soon": "bientôt",
    "later": "plus tard",
    "early": "tôt",
    "late": "tard",
    "weekly": "hebdomadaire",
    "monthly": "mensuel",
    "yearly": "annuel",
    "daily": "quotidien",
    "annually": "annuellement",
    "nowadays": "de nos jours",
    "currently": "actuellement",
    "presently": "actuellement",
    "lately": "dernièrement",
    "recently": "récemment",
    "formerly": "autrefois",
    "previously": "précédemment",
    "once": "une fois",
    "twice": "deux fois",
    "thrice": "trois fois",
    "first": "premier",
    "second": "deuxième",
    "third": "troisième",
    "last": "dernier",
    "next": "prochain",
    "previous": "précédent",
    "subsequent": "suivant",
    "consecutive": "consécutif",
    "successive": "successif",
    "alternate": "alternatif",
    "alternative": "alternatif",
    "other": "autre",
    "additional": "supplémentaire",
    "extra": "supplémentaire",
    "spare": "de rechange",
    "excess": "excès",
    "surplus": "surplus",
    "remaining": "restant",
    "leftover": "restant",
    "rest": "reste",
    "balance": "équilibre",
    "remainder": "reste",
    "residue": "résidu",
    "remnant": "vestige",
    "fragment": "fragment",
    "piece": "pièce",
    "part": "partie",
    "portion": "portion",
    "section": "section",
    "segment": "segment",
    "division": "division",
    "unit": "unité",
    "component": "composant",
    "element": "élément",
    "module": "module",
    "factor": "facteur",
    "feature": "caractéristique",
    "aspect": "aspect",
    "attribute": "attribut",
    "quality": "qualité",
    "property": "propriété",
    "trait": "trait",
    "characteristic": "caractéristique",
    "nature": "nature",
    "character": "caractère",
    "temperament": "tempérament",
    "personality": "personnalité",
    "behavior": "comportement",
    "conduct": "conduite",
    "manner": "manière",
    "way": "façon",
    "method": "méthode",
    "approach": "approche",
    "technique": "technique",
    "procedure": "procédure",
    "process": "processus",
    "operation": "opération",
    "action": "action",
    "activity": "activité",
    "performance": "performance",
    "execution": "exécution",
    "implementation": "mise en œuvre",
    "application": "application",
    "practice": "pratique",
    "exercise": "exercice",
    "training": "formation",
    "education": "éducation",
    "learning": "apprentissage",
    "study": "étude",
    "research": "recherche",
    "investigation": "enquête",
    "examination": "examen",
    "analysis": "analyse",
    "evaluation": "évaluation",
    "assessment": "évaluation",
    "judgment": "jugement",
    "opinion": "opinion",
    "view": "vue",
    "perspective": "perspective",
    "outlook": "perspective",
    "standpoint": "point de vue",
    "position": "position",
    "stance": "position",
    "attitude": "attitude",
    "feeling": "sentiment",
    "emotion": "émotion",
    "sensation": "sensation",
    "perception": "perception",
    "impression": "impression",
    "idea": "idée",
    "thought": "pensée",
    "notion": "notion",
    "concept": "concept",
    "conception": "conception",
    "understanding": "compréhension",
    "comprehension": "compréhension",
    "knowledge": "connaissance",
    "information": "information",
    "data": "données",
    "facts": "faits",
    "details": "détails",
    "particulars": "détails",
    "specifics": "spécificités",
    "points": "points",
    "items": "éléments",
    "things": "choses",
    "objects": "objets",
    "articles": "articles",
    "goods": "marchandises",
    "products": "produits",
    "merchandise": "marchandises",
    "wares": "articles",
    "commodities": "produits de base",
    "materials": "matériaux",
    "substances": "substances",
    "matter": "matière",
    "stuff": "trucs",
    "gear": "équipement",
    "equipment": "équipement",
    "apparatus": "appareil",
    "device": "appareil",
    "instrument": "instrument",
    "tool": "outil",
    "implement": "outil",
    "utensil": "ustensile",
    "appliance": "appareil",
    "machine": "machine",
    "mechanism": "mécanisme",
    "engine": "moteur",
    "motor": "moteur",
    "power": "puissance",
    "force": "force",
    "energy": "énergie",
    "strength": "force",
    "might": "puissance",
    "potency": "puissance",
    "vigor": "vigueur",
    "vitality": "vitalité",
    "life": "vie",
    "existence": "existence",
    "being": "être",
    "entity": "entité",
    "creature": "créature",
    "organism": "organisme",
    "individual": "individu",
    "person": "personne",
    "human": "humain",
    "man": "homme",
    "woman": "femme",
    "child": "enfant",
    "adult": "adulte",
    "people": "personnes",
    "public": "public",
    "crowd": "foule",
    "group": "groupe",
    "collection": "collection",
    "set": "ensemble",
    "series": "série",
    "sequence": "séquence",
    "succession": "succession",
    "progression": "progression",
    "order": "ordre",
    "arrangement": "arrangement",
    "organization": "organisation",
    "structure": "structure",
    "system": "système",
    "network": "réseau",
    "complex": "complexe",
    "compound": "composé",
    "composite": "composite",
    "mixture": "mélange",
    "blend": "mélange",
    "combination": "combinaison",
    "union": "union",
    "junction": "jonction",
    "connection": "connexion",
    "link": "lien",
    "relationship": "relation",
    "association": "association",
    "correlation": "corrélation",
    "correspondence": "correspondance",
    "similarity": "similarité",
    "resemblance": "ressemblance",
    "likeness": "ressemblance",
    "analogy": "analogie",
    "comparison": "comparaison",
    "contrast": "contraste",
    "difference": "différence",
    "distinction": "distinction",
    "variation": "variation",
    "variety": "variété",
    "diversity": "diversité",
    "range": "gamme",
    "scope": "portée",
    "extent": "étendue",
    "degree": "degré",
    "level": "niveau",
    "grade": "grade",
    "rank": "rang",
    "status": "statut",
    "position": "position",
    "place": "place",
    "location": "emplacement",
    "site": "site",
    "spot": "endroit",
    "point": "point",
    "area": "zone",
    "region": "région",
    "territory": "territoire",
    "zone": "zone",
    "district": "district",
    "sector": "secteur",
    "quarter": "quartier",
    "neighborhood": "quartier",
    "vicinity": "voisinage",
    "surroundings": "environs",
    "environment": "environnement",
    "habitat": "habitat",
    "ecosystem": "écosystème",
    "biosphere": "biosphère",
    "world": "monde",
    "earth": "terre",
    "globe": "globe",
    "planet": "planète",
    "universe": "univers",
    "cosmos": "cosmos",
    "space": "espace",
    "void": "vide",
    "vacuum": "vide",
    "emptiness": "vide",
    "nothingness": "néant",
    "absence": "absence",
    "lack": "manque",
    "want": "manque",
    "need": "besoin",
    "requirement": "exigence",
    "necessity": "nécessité",
    "essential": "essentiel",
    "vital": "vital",
    "critical": "critique",
    "crucial": "crucial",
    "important": "important",
    "significant": "significatif",
    "major": "majeur",
    "main": "principal",
    "primary": "primaire",
    "chief": "principal",
    "key": "clé",
    "central": "central",
    "core": "noyau",
    "heart": "cœur",
    "essence": "essence",
    "substance": "substance",
    "content": "contenu",
    "subject": "sujet",
    "topic": "sujet",
    "theme": "thème",
    "issue": "problème",
    "matter": "affaire",
    "affair": "affaire",
    "business": "affaire",
    "concern": "préoccupation",
    "interest": "intérêt",
    "attention": "attention",
    "focus": "focus",
    "concentration": "concentration",
    "emphasis": "accent",
    "stress": "stress",
    "pressure": "pression",
    "strain": "tension",
    "tension": "tension",
    "anxiety": "anxiété",
    "worry": "inquiétude",
    "concern": "préoccupation",
    "care": "soin",
    "caution": "prudence",
    "warning": "avertissement",
    "alert": "alerte",
    "alarm": "alarme",
    "danger": "danger",
    "hazard": "danger",
    "risk": "risque",
    "peril": "péril",
    "threat": "menace",
    "harm": "préjudice",
    "damage": "dommage",
    "injury": "blessure",
    "hurt": "blessure",
    "pain": "douleur",
    "suffering": "souffrance",
    "distress": "détresse",
    "misery": "misère",
    "agony": "agonie",
    "torment": "tourment",
    "torture": "torture",
    "anguish": "angoisse",
    "grief": "chagrin",
    "sorrow": "tristesse",
    "sadness": "tristesse",
    "unhappiness": "malheur",
    "depression": "dépression",
    "despair": "désespoir",
    "hopelessness": "désespoir",
    "gloom": "morosité",
    "doom": "destin",
    "fate": "destin",
    "destiny": "destinée",
    "fortune": "fortune",
    "luck": "chance",
    "chance": "hasard",
    "accident": "accident",
    "incident": "incident",
    "event": "événement",
    "occurrence": "occurrence",
    "happening": "événement",
    "circumstance": "circonstance",
    "situation": "situation",
    "condition": "condition",
    "state": "état",
    "status": "statut",
    "position": "position",
    "standing": "position",
    "rank": "rang",
    "class": "classe",
    "category": "catégorie",
    "classification": "classification",
    "type": "type",
    "kind": "genre",
    "sort": "sorte",
    "variety": "variété",
    "species": "espèce",
    "breed": "race",
    "strain": "souche",
    "family": "famille",
    "genus": "genre",
    "order": "ordre",
    "phylum": "embranchement",
    "kingdom": "règne",
    "domain": "domaine",
    "realm": "royaume",
    "sphere": "sphère",
    "field": "domaine",
    "area": "domaine",
    "domain": "domaine",
    "territory": "territoire",
    "province": "province",
    "region": "région",
    "district": "district",
    "zone": "zone",
    "sector": "secteur",
    "quarter": "quartier",
    "part": "partie",
    "section": "section",
    "segment": "segment",
    "division": "division",
    "portion": "portion",
    "piece": "pièce",
    "bit": "morceau",
    "fragment": "fragment",
    "chunk": "morceau",
    "lump": "morceau",
    "mass": "masse",
    "bulk": "masse",
    "volume": "volume",
    "quantity": "quantité",
    "amount": "montant",
    "number": "nombre",
    "figure": "chiffre",
    "digit": "chiffre",
    "numeral": "chiffre",
    "integer": "entier",
    "fraction": "fraction",
    "decimal": "décimal",
    "percentage": "pourcentage",
    "proportion": "proportion",
    "ratio": "rapport",
    "rate": "taux",
    "speed": "vitesse",
    "velocity": "vélocité",
    "pace": "rythme",
    "tempo": "tempo",
    "rhythm": "rythme",
    "beat": "battement",
    "pulse": "pouls",
    "throb": "battement",
    "palpitation": "palpitation",
    "flutter": "battement",
    "vibration": "vibration",
    "oscillation": "oscillation",
    "fluctuation": "fluctuation",
    "variation": "variation",
    "change": "changement",
    "alteration": "modification",
    "modification": "modification",
    "adjustment": "ajustement",
    "adaptation": "adaptation",
    "accommodation": "accommodation",
    "conformity": "conformité",
    "compliance": "conformité",
    "obedience": "obéissance",
    "submission": "soumission",
    "surrender": "reddition",
    "yield": "rendement",
    "production": "production",
    "output": "sortie",
    "product": "produit",
    "result": "résultat",
    "outcome": "résultat",
    "consequence": "conséquence",
    "effect": "effet",
    "impact": "impact",
    "influence": "influence",
    "power": "pouvoir",
    "authority": "autorité",
    "control": "contrôle",
    "command": "commande",
    "order": "ordre",
    "instruction": "instruction",
    "direction": "direction",
    "guidance": "orientation",
    "leadership": "leadership",
    "management": "gestion",
    "administration": "administration",
    "government": "gouvernement",
    "rule": "règle",